services:
  postgres:
    image: 'postgres:17.5-alpine'
    container_name: 'todo-management-db'
    environment:
      - 'POSTGRES_DB=todo-management'
      - 'POSTGRES_PASSWORD=pass'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: