CREATE TABLE IF NOT EXISTS TODO_ENTRIES
(
    ID          BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    TITLE       VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(500),
    IS_DONE  BOOLEAN     DEFAULT FALSE,
    EXPIRES_AT  TIMESTAMPTZ,
    CREATED_AT  TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT  TIMESTAMPTZ DEFAULT NOW()
);