CREATE TABLE IF NOT EXISTS TODO_ENTRIES
(
    ID          BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    TITLE       VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(500),
    IS_DONE     BOOLEAN     DEFAULT FALSE,
    EXPIRES_AT  TIMESTAMP,
    CREATED_AT  TIMESTAMP DEFAULT NOW(),
    UPDATED_AT  TIMESTAMP DEFAULT NOW()
);